development:
  adapter: postgresql
  encoding: unicode
  database: quest_dev
  pool: 5
  username: quest
  password: passwd1603
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: quest_test
  pool: 5
  username: quest
  password: passwd1603
  host: localhost
