development:
  adapter: postgresql
  encoding: unicode
  database: quest_dev
  pool: 5
  username: quest
  password: passwd1603
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: quest_test
  pool: 5
  username: quest
  password: passwd1603
  host: localhost

default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
